# Generated by Django 4.1.4 on 2022-12-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="post_author",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="likes",
            new_name="post_likes",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="title",
            new_name="post_title",
        ),
    ]
