# Generated by Django 4.1.4 on 2023-01-03 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0006_alter_comment_options_alter_post_post_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
