# Generated by Django 4.1.4 on 2022-12-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_comment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
    ]
